### ISSUE TITLE
What is the $JAVA_HOME

### ISSUE THREAD

**Issue by applar** [yahoo/CaffeOnSpark#112]
What is the $JAVA_HOME in Building for Spark 2.X?

**Comment by GnosisYu** [comment]
JAVA_HOME is an environment variable which is used to locate java while executing program.

**Comment by applar** [comment]
Thanks. I know that JAVA_HOME is an environment variable. But, I don't know which document it stand for. I want to set the environment variable, and, I don't know what I should do.

**Comment by GnosisYu** [comment]
@applar I think the document you are looking for is spark-env.sh.

**Comment by arundasan91** [comment]
Hello,

If you do `cd /usr/lib/jvm/` and explore, you'll see what versions of Java packages are installed. I understand that you know about environment variables. If I were you, I would set the environment variable in `.bashrc` file in the root folder and do `source .bashrc` to source it. 

If the Java version is `java-1.7.0-openjdk-amd64` I would add this line to `.bashrc` file.
```
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
```

To be honest I do not know if you are looking for this answer, if I misunderstood could you please elaborate so that I can try to help ?

Thanks,
Arun
