### ISSUE TITLE
How should i use the model which is preduced by demo for classing test_pictures

### ISSUE THREAD

**Issue by lklong** [yahoo/CaffeOnSpark#148]
i'm sorry for my english,i hope somebody help he and tell me how to use model preduced by demo.
Thanks very much!

**Comment by lklong** [comment]
another question is how to use the example (MyPipeLine)?????please tell me,if you know anything,thank you very much!!

**Comment by junshi15** [comment]
You can use the "-test" option to test your model.

For the pipeline example, it can be used the same way as you submit a spark job, i.e. spark-submit...
or you can use python as shown in the example below.
https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_python#run-examples

**Comment by anfeng** [comment]
@lklong For prediction, you should use "-features" for prediction in CLI. Here is the basic steps for lenet example. 

(1) Apply CaffeOnSpark "-train" to produce a model and save it to a file. 

`spark-submit --master ${MASTER_URL}     --files ${CAFFE_ON_SPARK}/data/lenet_memory_solver.prototxt,${CAFFE_ON_SPARK}/data/lenet_memory_train_test.prototxt     --conf spark.cores.max=${TOTAL_CORES}     --conf spark.task.cpus=${CORES_PER_WORKER}     --conf spark.driver.extraLibraryPath="${DYLD_LIBRARY_PATH}"     --conf spark.executorEnv.DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}"     --class com.yahoo.ml.caffe.CaffeOnSpark      ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar         **-train** -conf lenet_memory_solver.prototxt     -clusterSize ${SPARK_WORKER_INSTANCES}         -devices 1     -connection ethernet         -model **file:${CAFFE_ON_SPARK}/mnist_lenet.model**`

(2) Change batch_size of your test input data layer to 1.

`layer {
  name: "data"
  type: "MemoryData"
  top: "data"
  top: "label"
  include {
    phase: TEST
  }
  source_class: "com.yahoo.ml.caffe.LMDB"
  memory_data_param {
    source: "file:/Users/afeng/dev/ml/CaffeOnSpark/data/mnist_test_lmdb/"
    **batch_size: 1**
    channels: 1
    height: 28
    width: 28
    share_in_parallel: false
  }
  transform_param {
    scale: 0.00390625
  }
}`

(3) Apply CaffeOnSpark "-features" with the output of your top hidden layer (ex. ip2 in lenet_memory_train_test) using the model file saved in step (1), and save the prediction result into a file.

`spark-submit --master ${MASTER_URL}     --files ${CAFFE_ON_SPARK}/data/lenet_memory_solver.prototxt,${CAFFE_ON_SPARK}/data/lenet_memory_train_test.prototxt     --conf spark.cores.max=${TOTAL_CORES}     --conf spark.task.cpus=${CORES_PER_WORKER}     --conf spark.driver.extraLibraryPath="${DYLD_LIBRARY_PATH}"     --conf spark.executorEnv.DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}"     --class com.yahoo.ml.caffe.CaffeOnSpark      ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar **-features ip2** -conf lenet_memory_solver.prototxt     -clusterSize ${SPARK_WORKER_INSTANCES}         -devices 1     -connection ethernet         **-model file:${CAFFE_ON_SPARK}/mnist_lenet.model**         **-output file:${CAFFE_ON_SPARK}/lenet_features_result**`

(4) Process the output file from Step (3) to get your prediction result. In lenet network, ip2 has the probability of 10 digits, and you will need to find the index of the max value among these probabilities. In the following examples, sample 00000000 is predicted to 7 since its ip2[7] is the the largest among other ip2 values. 
`
{"SampleID":"00000000","ip2":[-0.53931516,-1.3817744,4.059077,3.8792288,-6.945209,-2.5439079,-9.267392,**15.677748**,-2.3044426,1.529253]}
{"SampleID":"00000001","ip2":[3.4058776,0.815202,**12.375869**,1.3219742,-5.6665177,-4.3718696,2.526735,-3.9186795,-1.4171885,-9.618664]}
`

You could apply the similar steps in Scala API or Python API. Our Python example is available at https://github.com/yahoo/CaffeOnSpark/blob/master/caffe-grid/src/main/python/examples/DLDemo.ipynb

**Comment by lklong** [comment]
thanks for all,i got it.and i write a demo,my may follow these steps
1.i train a caffemodel and validate the model 
2.i use the weight model from step 1st to extract the features of the train_data, and then i train a LogisticRegressionWithLBFGSModel with features of train_data ,finally i get a LRModel.
3.i use the LRModel to predict my test_data (ps:i extact features of the test_data ,i have used  weighted model from step 1st to extact features of the test_data),finally i get a result file of prediction.
note: i write my demo use scala.

thanks very much!
