### ISSUE TITLE
How can I build caffeonsparkpythonapi.zip?

### ISSUE THREAD

**Issue by itsfootball** [yahoo/CaffeOnSpark#164]
Sorry if this has been answered before, I am very new to spark and caffe and I have lots of questions. 

Do I need to provide the caffe python api everytime I run a spark-submit, even though caffe is installed on each of the workers that will be participating in the cluster?
Is ssh communication required to ship these files?
What are all the jar files and why do I need them?

Any input would be greatly appreciated.

**Comment by arundasan91** [comment]
Hello,
I can answer a few of your queries:

- SSH access: In almost all cluster setup, you will require bidirectional data flow. So all nodes will have to communicate with each other. What you should do is to set up the ssh keys in all nodes so that they can communicate without password. This is, in general, adding the public key in each nodes to the authorized keys.
- About this: "Do I need to provide the caffe python api everytime I run a spark-submit"
What are you trying to do here ? Are you using the command line interface to do follow the GetStarted guides like [GetStarted_yarn](https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_yarn) or trying Jupyter Notebooks like these [DLDemo](https://github.com/yahoo/CaffeOnSpark/blob/master/caffe-grid/src/main/python/examples/DLDemo.ipynb) ?

**Comment by itsfootball** [comment]
Arun, Thanks for the reply I have an ansible role that I can run to help me achieve just that, redistribution of public keys on each of the nodes and the master. Is ssh required in the event that I am using a spark-submit without any additional parameters such as the pythonapi.zip and the jar files?

**Comment by arundasan91** [comment]
Sorry for the late reply. In my understanding, you need to make sure that `ssh localhost` works without a password in a single node cluster and that you can ssh back and forth from all nodes in a multi-node cluster, regardless of the parameters you include. 

It is a hadoop/spark requirement I suppose. Namenode, Datanode in Hadoop should be configured for a passwordless ssh. Master and slaves in a Spark cluster too.

**Comment by itsfootball** [comment]
Thanks for the reply Arun, I'll try setting up key-based ssh authentication and see if anything changes in terms of the caffe module not being found as well.

**Comment by arundasan91** [comment]
"caffe module not being found as well"
-- did you mention that in your question ?

**Comment by itsfootball** [comment]
I did not mention that, not directly anyway. The issue that I am having with caffe is whenever I try to run a spark submit on a standalone cluster I get an error such as "caffe module not found" This does not seem to be an issue when I run a spark sumbit locally, the caffe module is found by spark and the job completes successfully.

I have posted this question on stackoverflow as well.
http://stackoverflow.com/q/39882281/6107394

**Comment by arundasan91** [comment]
I will have to ask a few questions in that case:

1. What is your OS ?
2. I suppose you want to use CaffeOnSpark in Python. Did you look into [https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_python](https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_python) ?
3. What is the command that you run for the above mentioned "whenever I try to run a spark submit on a standalone cluster"? Paste it here.
4. What is the command that you run for "when I run a spark sumbit locally, the caffe module is found by spark and the job completes successfully".

Thanks !

**Comment by itsfootball** [comment]
1. Ubuntu 16.04
2. I am not currently using caffeonspark, I build caffe from scratch from official git repository 
3. spark-submit --master spark://master-ip:7077 script.py
4. spark-submit --master local script.py (this works fine)

**Comment by arundasan91** [comment]
Oh I had this doubt when reading through the StackOverflow question.
@itsfootball , Please note that the CaffeOnSpark team ported Caffe to a distributed environment backed by Hadoop and Spark. You cannot, I am 99.99% sure, use Caffe alone in a Spark cluster or any distributed environment per se. (Caffe team is known to be working on this).

If you need distributed deep-learning using Caffe, please follow the building method mentioned here in [https://github.com/yahoo/CaffeOnSpark/wiki/build](https://github.com/yahoo/CaffeOnSpark/wiki/build) to build CaffeOnSpark for that and use CaffeOnSpark instead of Caffe. 

But, best bet will be to follow either this [GetStarted_standalone wiki](https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_standalone) or [GetStarted_yarn wiki](https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_yarn) to create you a distributed environment to carry out deep-learning.

Further, to add python, please go through [GetStarted_python wiki](https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_python).

Please let me know if it helped. I will post this answer to StackOverflow now.
Please close the issue and feel free to reopen it again if you have any doubts.

**Comment by itsfootball** [comment]
Ah got it, Thank you so much, this was very helpful.

I appreciate your patience on these questions.

**Comment by arundasan91** [comment]
No problem.
