### ISSUE TITLE
can i use CaffeOnSpark in windows ? or linux only ?

### ISSUE THREAD

**Issue by progbasma** [yahoo/CaffeOnSpark#230]
can i use CaffeOnSpark in windows ? or Linux only ? i need easy steps to setup CaffeOnSpark to use it in my project.

**Comment by junshi15** [comment]
It works on Linux, in particular we tested it on Ubuntu and RHEL. I do not know about Windows.

**Comment by progbasma** [comment]
thanks junshi15 , i am a beginner and i don't know the steps to work with caffeonspark to make video analysis project . does it need any hardware requirements to configure ? please, i need help

**Comment by junshi15** [comment]
You probably want to have some GPU since training on GPU is much fast. But for initial proof of concept, CPU will do. Also, you may want to start with caffe if you have no experience with deep learning, instead of going to caffeonspark directly.

**Comment by progbasma** [comment]
thank you for your reply.
my laptop has intel core i5 Proceesor ,4G Ram , ATI 5450 1G and 500G HardDisk
does it enough to make video retrieval implementation with CaffeOnSpark. or i need extra hardware requirements ?

which cluster manager can i use in my project without using extra hardware or money ?
Amazon EC2, Hadoop YARN cluster, openstack swift storage or Spark standalone cluster ?

i am a postgraduate student , i need simple steps to follow to configure and work with CaffeOnSpark for my project.
please help me ,

**Comment by arundasan91** [comment]
Hello @progbasma ,

Most of the deep learning problems are compute intense. The amount of resources needed depends upon your project itself (the size of input, number of layers in your network, size of dataset etc.).

Problems such as hand writing digits classification (MNIST) have lesser hardware requirements since the input size, size of dataset and the network itself is, compared to other networks and problems like ImageNet, Inception etc., small. So you should be able to train the network in your laptop provided you run it for a considerable amount of time for the learning to converge.

The cluster manager setup maybe chosen, IMHO, according to your need. 
- As you might already know, Amazon EC2 instances are pay-as-you-go cloud compute nodes which you can lease for 'x' hours and pay for the 'x' hours of usage according to the rate.
- OpenStack Swift storage is a cloud object storage node. This is available if you have set it up in an OpenStack cloud of your own.
- Hadoop Yarn is, IMHO, suitable if you have an existing Hadoop cluster.
- Spark standalone or a cluster is much more suitable since it supports Spark Dataframe, which in my tests gave better performance.

As @junshi15 mentioned, if you are just starting to develop your neural network, best way is to start with Caffe and see if your network builds and works the way you want (say in a small portion of your dataset). Then, you could easily port it to CaffeOnSpark given the networks 'prototxt' files.

If you want to check whether your Caffe proof-of-concept works on CaffeOnSpark, I would suggest trying it out in the [CaffeOnSpark Docker](https://github.com/yahoo/CaffeOnSpark/tree/master/docker) container.

Thanks,
Arun

**Comment by progbasma** [comment]
Hello @arundasan91 , thanks for your help.
i understood your steps . i wish i could implement it .

**Comment by progbasma** [comment]
thanks @arundasan91  for your help.
i understood your steps :)
